[package]
authors = ["alisa-lisa <alisa.dammer@gmail.com>", "svenstaro <svenstaro@gmail.com"]
name = "GameDev"
version = "0.1.0"
edition = "2018"

[dependencies]
tetra = "0.4"
shipyard = { version = "0.4", features = ["non_sync", "non_send"] }
rayon = "1.3"
ezing = "0.2"
